### ISSUE TITLE
Integration test using mock server or similar

### ISSUE THREAD

**Issue by andresdavid90** [andresdavid90/pizza-guy#22]

**Comment by baldore** [comment]
Ok.... we've a problem here. Right now we don't have an event when pizza-guy has completed the whole set of images. I was thinking about the singleton problem @andresdavid90, and I think we can take advantage of the `start` method that right now is not returning anything. Maybe we can expose an object or something there different that `this` that we can expand in a lot of different ways, like adding a Event Emitter (I have some ideas about this one), promise-like responses and other stuff. @alejandronanez @andresdavid90 let me know what do you think.

**Comment by andresdavid90** [comment]
I think we need to add the possibility to have separate instances of the module without breaking the current API.

For doing this, we would need to return a function instead of a literal object, but the function should have the same functionality attached in properties, just in the same way we are returning the literal object today.

If the user executes the function with a constructor call using `new`, we should be able to return a new object with the same exact API, with the difference that now you can create separate objects to respond the same API.

```javascript
import PizzaGuy from 'pizza-guy';
const pg = new PizzaGuy();

pg
  .deliver(images)
  .onAddress('./some-path')
  .onSuccess((info) => {
    console.log(`${info.fileName} succeed!`);
  })
  .onError((info) => {
    console.log(`${info.fileName} failed`);
  })
  .start();
```

@baldore @alejandronanez Too crazy?

**Comment by baldore** [comment]
Ok! I think if we change the currently returned object by a function, we can do this without breaking anything we have, since the module can still work as a singleton (The current methods will work as static methods of the constructor function) and with `new` we'll create a new instance. Another option is that if a method is called without a created instance, then it creates a new instance.

**Comment by andresdavid90** [comment]
Can you please explain how that last part would work?

**Comment by baldore** [comment]
I think it's very crazy actually. Maybe not a good idea but I'll share it anyway:

```javascript
function PizzaGuy() {

}

PizzaGuy.deliver = function(whatever) {
  // Here, we check if it's working as singleton and if that's the case, it creates a new instance
  if (!this instanceof PizzaGuy) {
    const pizzaGuy = new PizzaGuy();
    return pizzaGuy.deliver(whatever);
  }
}
```

I don't think is good because we should need to do this for each static method of PizzaGuy, but we could create a method that do this automatically. Let me know if I'm not crazy :camel:

**Comment by andresdavid90** [comment]
This is related to that conversation in the PR, but basically I think it is clever to not too clear for the user. Maybe using an explicit way as using the `new` operator would be better.

**Comment by baldore** [comment]
I'm gonna close this since this was some kind of spike to investigate. Even so, we would continue adding tests for `downloadFile` and `PizzaGuy`.
