### ISSUE TITLE
Refactor asynchronous tasks

### ISSUE THREAD

**Issue by baldore** [andresdavid90/pizza-guy#35]
Refactor any `Sync` functions and callbacks (when possible) to use a better alternative like `co` or `async/await`.

**Comment by andresdavid90** [comment]
@baldore Maybe we can start listing where do we need to do this. Any suggestions to start with?

**Comment by alejandronanez** [comment]
We should create a Milestone under issues.

**Comment by baldore** [comment]
This is more or less complete with the onComplete refactor. Also looks like the performance was improved, since we were able to remove the `this.timeout(4000);` in the onComplete test. Closing this.
