### ISSUE TITLE
Fix coverage

### ISSUE THREAD

**Issue by baldore** [andresdavid90/pizza-guy#48]
We need to figure out why the coverage is not working fine. This is related to the current configuration to the project.

**Comment by andresdavid90** [comment]
I'll review this issue this week.

**Comment by baldore** [comment]
I don't know if the problem is related to configuration inside codecov. Is it weird that structure appears as `src/src`?

![image](https://cloud.githubusercontent.com/assets/3131037/17859534/9e1cdc28-684f-11e6-8390-40c752618510.png)

**Comment by andresdavid90** [comment]
@baldore I'm trying to see what's up with that.

**Comment by andresdavid90** [comment]
I just wrote to the codecov support team. Waiting for response.

**Comment by andresdavid90** [comment]
This was fixed in the #51.
